-- 코드를 작성해주세요
SELECT YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) as YEAR, (YEAR_LIST.MAX_SIZE_OF_COLONY - ECOLI_DATA.SIZE_OF_COLONY) as YEAR_DEV, ECOLI_DATA.ID
FROM ECOLI_DATA
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) as MAX_SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR) YEAR_LIST
ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = YEAR_LIST.YEAR
ORDER BY YEAR, YEAR_DEV asc;